(function() {
	var vc = sap.viz.container;
	vc.declare("sap.viz.container.grace.constants.AppConst");

	var AppConst = sap.viz.container.grace.constants.AppConst;

	// Models
	AppConst.MODEL_GRACE = "MODEL_GRACE";

	// Mediators
	AppConst.MEDIATOR_GRACE_API = "MEDIATOR_GRACE_API";
	AppConst.MEDIATOR_COLUMN_LIST = "MEDIATOR_COLUMN_LIST";
	AppConst.MEDIATOR_COLUMN_X_AXIS = "MEDIATOR_COLUMN_X_AXIS";
	AppConst.MEDIATOR_COLUMN_Y_AXIS = "MEDIATOR_COLUMN_Y_AXIS";
	AppConst.MEDIATOR_COLUMN_MARKER = "MEDIATOR_COLUMN_MARKER";
	AppConst.MEDIATOR_VIZ_CONTAINER = "MEDIATOR_VIZ_CONTAINER";

	// Actions
	AppConst.ACTION_CHANGE_DATA_PROVIDER = "ACTION_CHANGE_DATA_PROVIDER";
	AppConst.ACTION_CHANGE_SELECTED_COLUMNS = "ACTION_CHANGE_SELECTED_COLUMNS";
	// Notifications
	AppConst.NOTIFICATION_DATA_PROVIDER_CHANGED = "NOTIFICATION_DATA_PROVIDER_CHANGED";
	AppConst.NOTIFICATION_SELECTED_COLUMNS_CHANGED = "NOTIFICATION_SELECTED_COLUMNS_CHANGED";

})();
